### PR TITLE
Adding my project on README.md

### PR DESCRIPTION
**Pull request by Pedro-A-D-S**

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Thanks a lot @Pedro-A-D-S ! Could you signoff your commit so that the DCO check passes? you have the instructions in https://github.com/kedro-org/awesome-kedro/pull/19/checks?check_run_id=16626480094

**Comment by Pedro-A-D-S** [comment]
The pleasure is mine, I did it right now. Please check if anything went wrong whenever you can :)

**Comment by astrojuanlu** [comment]
I think nothing happened, maybe you forgot to force push?

**Comment by astrojuanlu** [comment]
Closing in favour of #19

**Pull request closed without merging**
