### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pedro-A-D-S**
Adding Diamond Price Prediction project on README.md file.

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
Thanks a lot!

**Comment by astrojuanlu** [comment]
Could you please signoff your commit so the DCO check passes? If you click on it you will find instructions. If it was only one commit you can do `git commit --amend --signoff --no-edit`, if you had more, `git rebase --signoff`. After rewriting the history you will need to do `git push --force`.

And if you keep working on this branch, please use the `-s/--signoff` flag when committing, for example `git commit -s -m 'Add feature'`.

**Comment by Pedro-A-D-S** [comment]
I believe now I did it correctly, thanks for your patience!

**Comment by astrojuanlu** [comment]
Hey @Pedro-A-D-S , I don't see changes here - maybe you need to force push still?

**Comment by astrojuanlu** [comment]
Went ahead and merged this, thanks @Pedro-A-D-S!

**Pull request merged**
